<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_242-release) on Wed Jun 10 21:07:08 CEST 2020 -->
<title>C-Index</title>
<meta name="date" content="2020-06-10">
<link rel="stylesheet" type="text/css" href="../stylesheet.css" title="Style">
<script type="text/javascript" src="../script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="C-Index";
        }
    }
    catch(err) {
    }
//-->
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../com/example/billsreminderapp/package-summary.html">Package</a></li>
<li>Class</li>
<li><a href="../overview-tree.html">Tree</a></li>
<li><a href="../deprecated-list.html">Deprecated</a></li>
<li class="navBarCell1Rev">Index</li>
<li><a href="../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="index-2.html">Prev Letter</a></li>
<li><a href="index-4.html">Next Letter</a></li>
</ul>
<ul class="navList">
<li><a href="../index.html?index-files/index-3.html" target="_top">Frames</a></li>
<li><a href="index-3.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<div class="contentContainer"><a href="index-1.html">A</a>&nbsp;<a href="index-2.html">B</a>&nbsp;<a href="index-3.html">C</a>&nbsp;<a href="index-4.html">D</a>&nbsp;<a href="index-5.html">E</a>&nbsp;<a href="index-6.html">G</a>&nbsp;<a href="index-7.html">H</a>&nbsp;<a href="index-8.html">I</a>&nbsp;<a href="index-9.html">L</a>&nbsp;<a href="index-10.html">M</a>&nbsp;<a href="index-11.html">N</a>&nbsp;<a href="index-12.html">O</a>&nbsp;<a href="index-13.html">R</a>&nbsp;<a href="index-14.html">S</a>&nbsp;<a href="index-15.html">T</a>&nbsp;<a href="index-16.html">V</a>&nbsp;<a href="index-17.html">W</a>&nbsp;<a name="I:C">
<!--   -->
</a>
<h2 class="title">C</h2>
<dl>
<dt><a href="../com/example/billsreminderapp/Cache.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Cache</span></a> - Class in <a href="../com/example/billsreminderapp/package-summary.html">com.example.billsreminderapp</a></dt>
<dd>
<div class="block">Cache storage class used to handle invoices</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/Cache.html#Cache--">Cache()</a></span> - Constructor for class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/Cache.html" title="class in com.example.billsreminderapp">Cache</a></dt>
<dd>&nbsp;</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/Cache.html#cache">cache</a></span> - Static variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/Cache.html" title="class in com.example.billsreminderapp">Cache</a></dt>
<dd>
<div class="block">new object cache</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/AddActivity.html#cancel-android.view.View-">cancel(View)</a></span> - Method in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/AddActivity.html" title="class in com.example.billsreminderapp">AddActivity</a></dt>
<dd>
<div class="block">function leading to the main activity</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/AddActivity.html#charge">charge</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/AddActivity.html" title="class in com.example.billsreminderapp">AddActivity</a></dt>
<dd>
<div class="block">variable charge is used to enter text by the user</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/CustomAdapter.ViewHolder.html#charge">charge</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/CustomAdapter.ViewHolder.html" title="class in com.example.billsreminderapp">CustomAdapter.ViewHolder</a></dt>
<dd>
<div class="block">TextView for user to see in charge field.</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/Invoice.html#charge">charge</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a></dt>
<dd>&nbsp;</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/AddActivity.html#chooseDate">chooseDate</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/AddActivity.html" title="class in com.example.billsreminderapp">AddActivity</a></dt>
<dd>&nbsp;</dd>
<dt><a href="../com/example/billsreminderapp/package-summary.html">com.example.billsreminderapp</a> - package com.example.billsreminderapp</dt>
<dd>&nbsp;</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/AddActivity.html#comments">comments</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/AddActivity.html" title="class in com.example.billsreminderapp">AddActivity</a></dt>
<dd>
<div class="block">variable charge is used to enter text by the user</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/CustomAdapter.ViewHolder.html#comments">comments</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/CustomAdapter.ViewHolder.html" title="class in com.example.billsreminderapp">CustomAdapter.ViewHolder</a></dt>
<dd>
<div class="block">TextView for user to see in comments field.</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/Invoice.html#comments">comments</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a></dt>
<dd>&nbsp;</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/Invoice.html#compareTo-java.lang.Object-">compareTo(Object)</a></span> - Method in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a></dt>
<dd>&nbsp;</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/NotificationSetter.html#context">context</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/NotificationSetter.html" title="class in com.example.billsreminderapp">NotificationSetter</a></dt>
<dd>&nbsp;</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/MainActivity.html#CONTEXT_MENU_DELETE">CONTEXT_MENU_DELETE</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/MainActivity.html" title="class in com.example.billsreminderapp">MainActivity</a></dt>
<dd>
<div class="block">This variable is used to delete items from the invoice list</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/MainActivity.html#CONTEXT_MENU_EDIT">CONTEXT_MENU_EDIT</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/MainActivity.html" title="class in com.example.billsreminderapp">MainActivity</a></dt>
<dd>
<div class="block">This variable is used to modify items from the invoice list</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/MainActivity.html#CONTEXT_MENU_MARK_AS_PAID">CONTEXT_MENU_MARK_AS_PAID</a></span> - Variable in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/MainActivity.html" title="class in com.example.billsreminderapp">MainActivity</a></dt>
<dd>
<div class="block">This variable is used to mark payments as paid on the invoice list</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/NotificationSetter.html#createRepeatNotification--">createRepeatNotification()</a></span> - Method in class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/NotificationSetter.html" title="class in com.example.billsreminderapp">NotificationSetter</a></dt>
<dd>
<div class="block">This method is used to create repeat notification.</div>
</dd>
<dt><a href="../com/example/billsreminderapp/CustomAdapter.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">CustomAdapter</span></a> - Class in <a href="../com/example/billsreminderapp/package-summary.html">com.example.billsreminderapp</a></dt>
<dd>
<div class="block">Class responsible for display invoices data in main layout (receiver,charge,datePayment,comments)</div>
</dd>
<dt><span class="memberNameLink"><a href="../com/example/billsreminderapp/CustomAdapter.html#CustomAdapter-java.util.ArrayList-android.content.Context-android.app.Activity-">CustomAdapter(ArrayList&lt;Invoice&gt;, Context, Activity)</a></span> - Constructor for class com.example.billsreminderapp.<a href="../com/example/billsreminderapp/CustomAdapter.html" title="class in com.example.billsreminderapp">CustomAdapter</a></dt>
<dd>
<div class="block">Class constructor</div>
</dd>
<dt><a href="../com/example/billsreminderapp/CustomAdapter.ViewHolder.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">CustomAdapter.ViewHolder</span></a> - Class in <a href="../com/example/billsreminderapp/package-summary.html">com.example.billsreminderapp</a></dt>
<dd>
<div class="block">Class that stores data displayed on main activity.</div>
</dd>
</dl>
<a href="index-1.html">A</a>&nbsp;<a href="index-2.html">B</a>&nbsp;<a href="index-3.html">C</a>&nbsp;<a href="index-4.html">D</a>&nbsp;<a href="index-5.html">E</a>&nbsp;<a href="index-6.html">G</a>&nbsp;<a href="index-7.html">H</a>&nbsp;<a href="index-8.html">I</a>&nbsp;<a href="index-9.html">L</a>&nbsp;<a href="index-10.html">M</a>&nbsp;<a href="index-11.html">N</a>&nbsp;<a href="index-12.html">O</a>&nbsp;<a href="index-13.html">R</a>&nbsp;<a href="index-14.html">S</a>&nbsp;<a href="index-15.html">T</a>&nbsp;<a href="index-16.html">V</a>&nbsp;<a href="index-17.html">W</a>&nbsp;</div>
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../com/example/billsreminderapp/package-summary.html">Package</a></li>
<li>Class</li>
<li><a href="../overview-tree.html">Tree</a></li>
<li><a href="../deprecated-list.html">Deprecated</a></li>
<li class="navBarCell1Rev">Index</li>
<li><a href="../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="index-2.html">Prev Letter</a></li>
<li><a href="index-4.html">Next Letter</a></li>
</ul>
<ul class="navList">
<li><a href="../index.html?index-files/index-3.html" target="_top">Frames</a></li>
<li><a href="index-3.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</body>
</html>
