<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_242-release) on Wed Jun 10 21:07:07 CEST 2020 -->
<title>Cache</title>
<meta name="date" content="2020-06-10">
<link rel="stylesheet" type="text/css" href="../../../stylesheet.css" title="Style">
<script type="text/javascript" src="../../../script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="Cache";
        }
    }
    catch(err) {
    }
//-->
var methods = {"i0":10,"i1":9,"i2":10,"i3":10,"i4":10};
var tabs = {65535:["t0","All Methods"],1:["t1","Static Methods"],2:["t2","Instance Methods"],8:["t4","Concrete Methods"]};
var altColor = "altColor";
var rowColor = "rowColor";
var tableTab = "tableTab";
var activeTableTab = "activeTableTab";
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../com/example/billsreminderapp/package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-files/index-1.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="../../../com/example/billsreminderapp/AddActivity.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
<li><a href="../../../com/example/billsreminderapp/CustomAdapter.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../../../index.html?com/example/billsreminderapp/Cache.html" target="_top">Frames</a></li>
<li><a href="Cache.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li><a href="#field.summary">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#constructor.summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li><a href="#field.detail">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#constructor.detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">com.example.billsreminderapp</div>
<h2 title="Class Cache" class="title">Class Cache</h2>
</div>
<div class="contentContainer">
<ul class="inheritance">
<li>java.lang.Object</li>
<li>
<ul class="inheritance">
<li>com.example.billsreminderapp.Cache</li>
</ul>
</li>
</ul>
<div class="description">
<ul class="blockList">
<li class="blockList">
<hr>
<br>
<pre>class <span class="typeNameLabel">Cache</span>
extends java.lang.Object</pre>
<div class="block">Cache storage class used to handle invoices</div>
<dl>
<dt><span class="simpleTagLabel">Author:</span></dt>
<dd>Michal Borkowski, Kamil Szczepanik</dd>
</dl>
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
<!-- =========== FIELD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="field.summary">
<!--   -->
</a>
<h3>Field Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Field Summary table, listing fields, and an explanation">
<caption><span>Fields</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Field and Description</th>
</tr>
<tr class="altColor">
<td class="colFirst"><code>private static <a href="../../../com/example/billsreminderapp/Cache.html" title="class in com.example.billsreminderapp">Cache</a></code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#cache">cache</a></span></code>
<div class="block">new object cache</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>private <a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a></code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#editedInvoice">editedInvoice</a></span></code>
<div class="block">variable to edit invoice</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>private <a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a></code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#markedInvoice">markedInvoice</a></span></code>
<div class="block">variable to mark invoice</div>
</td>
</tr>
</table>
</li>
</ul>
<!-- ======== CONSTRUCTOR SUMMARY ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor.summary">
<!--   -->
</a>
<h3>Constructor Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Constructor Summary table, listing constructors, and an explanation">
<caption><span>Constructors</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colOne" scope="col">Constructor and Description</th>
</tr>
<tr class="altColor">
<td class="colOne"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#Cache--">Cache</a></span>()</code>&nbsp;</td>
</tr>
</table>
</li>
</ul>
<!-- ========== METHOD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="method.summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Method Summary table, listing methods, and an explanation">
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t1" class="tableTab"><span><a href="javascript:show(1);">Static Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t2" class="tableTab"><span><a href="javascript:show(2);">Instance Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t4" class="tableTab"><span><a href="javascript:show(8);">Concrete Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tr id="i0" class="altColor">
<td class="colFirst"><code>(package private) <a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a></code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#getEditedInvoice--">getEditedInvoice</a></span>()</code>
<div class="block">Gets edited invoice.</div>
</td>
</tr>
<tr id="i1" class="rowColor">
<td class="colFirst"><code>(package private) static <a href="../../../com/example/billsreminderapp/Cache.html" title="class in com.example.billsreminderapp">Cache</a></code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#getInstance--">getInstance</a></span>()</code>
<div class="block">This method is used to gets cache object.</div>
</td>
</tr>
<tr id="i2" class="altColor">
<td class="colFirst"><code>(package private) <a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a></code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#getMarkedInvoice--">getMarkedInvoice</a></span>()</code>
<div class="block">This method is used to gets marked invoice.</div>
</td>
</tr>
<tr id="i3" class="rowColor">
<td class="colFirst"><code>(package private) void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#setEditedInvoice-com.example.billsreminderapp.Invoice-">setEditedInvoice</a></span>(<a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a>&nbsp;editedInvoice)</code>
<div class="block">Sets edited invoice.</div>
</td>
</tr>
<tr id="i4" class="altColor">
<td class="colFirst"><code>(package private) void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Cache.html#setMarkedInvoice-com.example.billsreminderapp.Invoice-">setMarkedInvoice</a></span>(<a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a>&nbsp;markedInvoice)</code>
<div class="block">This method is used to sets marked invoice.</div>
</td>
</tr>
</table>
<ul class="blockList">
<li class="blockList"><a name="methods.inherited.from.class.java.lang.Object">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;java.lang.Object</h3>
<code>clone, equals, finalize, getClass, hashCode, notify, notifyAll, toString, wait, wait, wait</code></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
<!-- ============ FIELD DETAIL =========== -->
<ul class="blockList">
<li class="blockList"><a name="field.detail">
<!--   -->
</a>
<h3>Field Detail</h3>
<a name="markedInvoice">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>markedInvoice</h4>
<pre>private&nbsp;<a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a> markedInvoice</pre>
<div class="block">variable to mark invoice</div>
</li>
</ul>
<a name="editedInvoice">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>editedInvoice</h4>
<pre>private&nbsp;<a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a> editedInvoice</pre>
<div class="block">variable to edit invoice</div>
</li>
</ul>
<a name="cache">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>cache</h4>
<pre>private static final&nbsp;<a href="../../../com/example/billsreminderapp/Cache.html" title="class in com.example.billsreminderapp">Cache</a> cache</pre>
<div class="block">new object cache</div>
</li>
</ul>
</li>
</ul>
<!-- ========= CONSTRUCTOR DETAIL ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor.detail">
<!--   -->
</a>
<h3>Constructor Detail</h3>
<a name="Cache--">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>Cache</h4>
<pre>Cache()</pre>
</li>
</ul>
</li>
</ul>
<!-- ============ METHOD DETAIL ========== -->
<ul class="blockList">
<li class="blockList"><a name="method.detail">
<!--   -->
</a>
<h3>Method Detail</h3>
<a name="getInstance--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getInstance</h4>
<pre>static&nbsp;<a href="../../../com/example/billsreminderapp/Cache.html" title="class in com.example.billsreminderapp">Cache</a>&nbsp;getInstance()</pre>
<div class="block">This method is used to gets cache object.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>cache object</dd>
</dl>
</li>
</ul>
<a name="getMarkedInvoice--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getMarkedInvoice</h4>
<pre><a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a>&nbsp;getMarkedInvoice()</pre>
<div class="block">This method is used to gets marked invoice.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>object markedInvoice</dd>
</dl>
</li>
</ul>
<a name="setMarkedInvoice-com.example.billsreminderapp.Invoice-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setMarkedInvoice</h4>
<pre>void&nbsp;setMarkedInvoice(<a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a>&nbsp;markedInvoice)</pre>
<div class="block">This method is used to sets marked invoice.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>markedInvoice</code> - variable to mark invoice</dd>
</dl>
</li>
</ul>
<a name="getEditedInvoice--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getEditedInvoice</h4>
<pre><a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a>&nbsp;getEditedInvoice()</pre>
<div class="block">Gets edited invoice.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>object editedInvoice</dd>
</dl>
</li>
</ul>
<a name="setEditedInvoice-com.example.billsreminderapp.Invoice-">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>setEditedInvoice</h4>
<pre>void&nbsp;setEditedInvoice(<a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a>&nbsp;editedInvoice)</pre>
<div class="block">Sets edited invoice.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>editedInvoice</code> - variable to edited invoice</dd>
</dl>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../com/example/billsreminderapp/package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-files/index-1.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="../../../com/example/billsreminderapp/AddActivity.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
<li><a href="../../../com/example/billsreminderapp/CustomAdapter.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../../../index.html?com/example/billsreminderapp/Cache.html" target="_top">Frames</a></li>
<li><a href="Cache.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li><a href="#field.summary">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#constructor.summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li><a href="#field.detail">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#constructor.detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</body>
</html>
