<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_242-release) on Wed Jun 10 21:07:07 CEST 2020 -->
<title>Invoice</title>
<meta name="date" content="2020-06-10">
<link rel="stylesheet" type="text/css" href="../../../stylesheet.css" title="Style">
<script type="text/javascript" src="../../../script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="Invoice";
        }
    }
    catch(err) {
    }
//-->
var methods = {"i0":10,"i1":10,"i2":10,"i3":10,"i4":10,"i5":10,"i6":10,"i7":10,"i8":10,"i9":10,"i10":10,"i11":10,"i12":10,"i13":10,"i14":10,"i15":10,"i16":10,"i17":10,"i18":10,"i19":10,"i20":10,"i21":10,"i22":10};
var tabs = {65535:["t0","All Methods"],2:["t2","Instance Methods"],8:["t4","Concrete Methods"]};
var altColor = "altColor";
var rowColor = "rowColor";
var tableTab = "tableTab";
var activeTableTab = "activeTableTab";
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../com/example/billsreminderapp/package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-files/index-1.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="../../../com/example/billsreminderapp/CustomAdapter.ViewHolder.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
<li><a href="../../../com/example/billsreminderapp/InvoicesManager.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../../../index.html?com/example/billsreminderapp/Invoice.html" target="_top">Frames</a></li>
<li><a href="Invoice.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li><a href="#field.summary">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#constructor.summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li><a href="#field.detail">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#constructor.detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">com.example.billsreminderapp</div>
<h2 title="Class Invoice" class="title">Class Invoice</h2>
</div>
<div class="contentContainer">
<ul class="inheritance">
<li>java.lang.Object</li>
<li>
<ul class="inheritance">
<li>com.example.billsreminderapp.Invoice</li>
</ul>
</li>
</ul>
<div class="description">
<ul class="blockList">
<li class="blockList">
<dl>
<dt>All Implemented Interfaces:</dt>
<dd>java.lang.Comparable</dd>
</dl>
<hr>
<br>
<pre>public class <span class="typeNameLabel">Invoice</span>
extends java.lang.Object
implements java.lang.Comparable</pre>
<div class="block">Invoice class represents class definition</div>
<dl>
<dt><span class="simpleTagLabel">Author:</span></dt>
<dd>Michal Borkowski, Kamil Szczepanik</dd>
</dl>
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
<!-- =========== FIELD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="field.summary">
<!--   -->
</a>
<h3>Field Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Field Summary table, listing fields, and an explanation">
<caption><span>Fields</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Field and Description</th>
</tr>
<tr class="altColor">
<td class="colFirst"><code>private java.lang.Double</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#charge">charge</a></span></code>&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>private java.lang.String</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#comments">comments</a></span></code>&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>private java.lang.Integer</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#howManyTimesPayment">howManyTimesPayment</a></span></code>&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>private boolean</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#isPaid">isPaid</a></span></code>&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>private boolean</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#isRepeated">isRepeated</a></span></code>&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>private java.lang.String</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#receiver">receiver</a></span></code>&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>private java.lang.String</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#repetitionPeriod">repetitionPeriod</a></span></code>&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>private java.util.Date</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#term">term</a></span></code>&nbsp;</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>private java.lang.Integer</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#whenInform">whenInform</a></span></code>&nbsp;</td>
</tr>
</table>
</li>
</ul>
<!-- ======== CONSTRUCTOR SUMMARY ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor.summary">
<!--   -->
</a>
<h3>Constructor Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Constructor Summary table, listing constructors, and an explanation">
<caption><span>Constructors</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colOne" scope="col">Constructor and Description</th>
</tr>
<tr class="altColor">
<td class="colOne"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#Invoice-java.lang.String-java.lang.Double-java.lang.String-java.lang.Integer-">Invoice</a></span>(java.lang.String&nbsp;receiver,
       java.lang.Double&nbsp;charge,
       java.lang.String&nbsp;term,
       java.lang.Integer&nbsp;whenInform)</code>
<div class="block">Constructor with basic parameters</div>
</td>
</tr>
<tr class="rowColor">
<td class="colOne"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#Invoice-java.lang.String-java.lang.Double-java.lang.String-java.lang.String-">Invoice</a></span>(java.lang.String&nbsp;receiver,
       java.lang.Double&nbsp;charge,
       java.lang.String&nbsp;term,
       java.lang.String&nbsp;comments)</code>
<div class="block">Constructor with basic parameters</div>
</td>
</tr>
</table>
</li>
</ul>
<!-- ========== METHOD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="method.summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Method Summary table, listing methods, and an explanation">
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t2" class="tableTab"><span><a href="javascript:show(2);">Instance Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t4" class="tableTab"><span><a href="javascript:show(8);">Concrete Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tr id="i0" class="altColor">
<td class="colFirst"><code>int</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#compareTo-java.lang.Object-">compareTo</a></span>(java.lang.Object&nbsp;o)</code>&nbsp;</td>
</tr>
<tr id="i1" class="rowColor">
<td class="colFirst"><code>boolean</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#equals-java.lang.Object-">equals</a></span>(java.lang.Object&nbsp;o)</code>
<div class="block">This method is used to comparing object invoice.</div>
</td>
</tr>
<tr id="i2" class="altColor">
<td class="colFirst"><code>(package private) void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#extendTime--">extendTime</a></span>()</code>
<div class="block">This method is used to date in invoice will be added next payment time</div>
</td>
</tr>
<tr id="i3" class="rowColor">
<td class="colFirst"><code>(package private) java.lang.Double</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getCharge--">getCharge</a></span>()</code>
<div class="block">This method is used to gets value of charge.</div>
</td>
</tr>
<tr id="i4" class="altColor">
<td class="colFirst"><code>(package private) java.lang.String</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getComments--">getComments</a></span>()</code>
<div class="block">This method is used to gets comments.</div>
</td>
</tr>
<tr id="i5" class="rowColor">
<td class="colFirst"><code>(package private) java.lang.Integer</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getHowManyTimesPayment--">getHowManyTimesPayment</a></span>()</code>
<div class="block">This method is used to gets the number of payments made.</div>
</td>
</tr>
<tr id="i6" class="altColor">
<td class="colFirst"><code>(package private) java.lang.String</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getReceiver--">getReceiver</a></span>()</code>
<div class="block">This method is used to gets value of receiver.</div>
</td>
</tr>
<tr id="i7" class="rowColor">
<td class="colFirst"><code>(package private) java.lang.String</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getRepetitionPeriod--">getRepetitionPeriod</a></span>()</code>
<div class="block">This method is used to gets value of repetitionPeriod.</div>
</td>
</tr>
<tr id="i8" class="altColor">
<td class="colFirst"><code>(package private) java.util.Date</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getTerm--">getTerm</a></span>()</code>
<div class="block">This method is used to gets value of term.</div>
</td>
</tr>
<tr id="i9" class="rowColor">
<td class="colFirst"><code>(package private) java.lang.String</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getTermString--">getTermString</a></span>()</code>
<div class="block">This method is used to gets value of term.</div>
</td>
</tr>
<tr id="i10" class="altColor">
<td class="colFirst"><code>(package private) java.lang.String</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getTimeToDisplay--">getTimeToDisplay</a></span>()</code>
<div class="block">This method is used to gets time to display.</div>
</td>
</tr>
<tr id="i11" class="rowColor">
<td class="colFirst"><code>(package private) java.lang.Integer</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#getWhenInform--">getWhenInform</a></span>()</code>
<div class="block">This method is used to gets value of variable whenInform</div>
</td>
</tr>
<tr id="i12" class="altColor">
<td class="colFirst"><code>int</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#hashCode--">hashCode</a></span>()</code>
<div class="block">This method returns the hashcode value as an Integer.</div>
</td>
</tr>
<tr id="i13" class="rowColor">
<td class="colFirst"><code>boolean</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#isisPaid--">isisPaid</a></span>()</code>
<div class="block">This method is used to check if an invoice has been paid.</div>
</td>
</tr>
<tr id="i14" class="altColor">
<td class="colFirst"><code>(package private) boolean</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#isRepeated--">isRepeated</a></span>()</code>
<div class="block">This method is used to determine if payments will be repeated.</div>
</td>
</tr>
<tr id="i15" class="rowColor">
<td class="colFirst"><code>void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#setCharge-java.lang.Double-">setCharge</a></span>(java.lang.Double&nbsp;charge)</code>
<div class="block">This method is used to sets value of charge.</div>
</td>
</tr>
<tr id="i16" class="altColor">
<td class="colFirst"><code>void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#setComments-java.lang.String-">setComments</a></span>(java.lang.String&nbsp;comments)</code>
<div class="block">This method is used to sets comments.</div>
</td>
</tr>
<tr id="i17" class="rowColor">
<td class="colFirst"><code>(package private) void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#setHowManyTimesPayment-java.lang.Integer-">setHowManyTimesPayment</a></span>(java.lang.Integer&nbsp;howManyTimesPayment)</code>
<div class="block">This method is used to sets value of how many times are payments.</div>
</td>
</tr>
<tr id="i18" class="altColor">
<td class="colFirst"><code>(package private) void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#setIsRepeated-boolean-">setIsRepeated</a></span>(boolean&nbsp;isRepeated)</code>
<div class="block">This method is used to sets value of isRepeated.</div>
</td>
</tr>
<tr id="i19" class="rowColor">
<td class="colFirst"><code>void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#setReceiver-java.lang.String-">setReceiver</a></span>(java.lang.String&nbsp;receiver)</code>
<div class="block">This method is used to sets value of receiver.</div>
</td>
</tr>
<tr id="i20" class="altColor">
<td class="colFirst"><code>(package private) void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#setRepetitionPeriod-java.lang.String-">setRepetitionPeriod</a></span>(java.lang.String&nbsp;repetitionPeriod)</code>
<div class="block">This method is used to sets value of repetitionPeriod.</div>
</td>
</tr>
<tr id="i21" class="rowColor">
<td class="colFirst"><code>private void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#setTerm-java.util.Date-">setTerm</a></span>(java.util.Date&nbsp;term)</code>
<div class="block">This method is used to sets value of variable term</div>
</td>
</tr>
<tr id="i22" class="altColor">
<td class="colFirst"><code>(package private) void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../com/example/billsreminderapp/Invoice.html#setWhenInform-java.lang.Integer-">setWhenInform</a></span>(java.lang.Integer&nbsp;whenInform)</code>
<div class="block">This method is used to sets value of whenInform.</div>
</td>
</tr>
</table>
<ul class="blockList">
<li class="blockList"><a name="methods.inherited.from.class.java.lang.Object">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;java.lang.Object</h3>
<code>clone, finalize, getClass, notify, notifyAll, toString, wait, wait, wait</code></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
<!-- ============ FIELD DETAIL =========== -->
<ul class="blockList">
<li class="blockList"><a name="field.detail">
<!--   -->
</a>
<h3>Field Detail</h3>
<a name="receiver">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>receiver</h4>
<pre>private&nbsp;java.lang.String receiver</pre>
</li>
</ul>
<a name="charge">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>charge</h4>
<pre>private&nbsp;java.lang.Double charge</pre>
</li>
</ul>
<a name="term">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>term</h4>
<pre>private&nbsp;java.util.Date term</pre>
</li>
</ul>
<a name="comments">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>comments</h4>
<pre>private&nbsp;java.lang.String comments</pre>
</li>
</ul>
<a name="howManyTimesPayment">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>howManyTimesPayment</h4>
<pre>private&nbsp;java.lang.Integer howManyTimesPayment</pre>
</li>
</ul>
<a name="isRepeated">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>isRepeated</h4>
<pre>private&nbsp;boolean isRepeated</pre>
</li>
</ul>
<a name="repetitionPeriod">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>repetitionPeriod</h4>
<pre>private&nbsp;java.lang.String repetitionPeriod</pre>
</li>
</ul>
<a name="whenInform">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>whenInform</h4>
<pre>private&nbsp;java.lang.Integer whenInform</pre>
</li>
</ul>
<a name="isPaid">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>isPaid</h4>
<pre>private&nbsp;boolean isPaid</pre>
</li>
</ul>
</li>
</ul>
<!-- ========= CONSTRUCTOR DETAIL ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor.detail">
<!--   -->
</a>
<h3>Constructor Detail</h3>
<a name="Invoice-java.lang.String-java.lang.Double-java.lang.String-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>Invoice</h4>
<pre>Invoice(java.lang.String&nbsp;receiver,
        java.lang.Double&nbsp;charge,
        java.lang.String&nbsp;term,
        java.lang.String&nbsp;comments)</pre>
<div class="block">Constructor with basic parameters</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>receiver</code> - variable receiver</dd>
<dd><code>charge</code> - variable charge</dd>
<dd><code>term</code> - variable term</dd>
<dd><code>comments</code> - variable comments</dd>
</dl>
</li>
</ul>
<a name="Invoice-java.lang.String-java.lang.Double-java.lang.String-java.lang.Integer-">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>Invoice</h4>
<pre>Invoice(java.lang.String&nbsp;receiver,
        java.lang.Double&nbsp;charge,
        java.lang.String&nbsp;term,
        java.lang.Integer&nbsp;whenInform)</pre>
<div class="block">Constructor with basic parameters</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>receiver</code> - variable receiver</dd>
<dd><code>charge</code> - variable charge</dd>
<dd><code>term</code> - variable term</dd>
<dd><code>whenInform</code> - variable is used to set inform time</dd>
</dl>
</li>
</ul>
</li>
</ul>
<!-- ============ METHOD DETAIL ========== -->
<ul class="blockList">
<li class="blockList"><a name="method.detail">
<!--   -->
</a>
<h3>Method Detail</h3>
<a name="extendTime--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>extendTime</h4>
<pre>void&nbsp;extendTime()</pre>
<div class="block">This method is used to date in invoice will be added next payment time</div>
</li>
</ul>
<a name="getReceiver--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getReceiver</h4>
<pre>java.lang.String&nbsp;getReceiver()</pre>
<div class="block">This method is used to gets value of receiver.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>string value of receiver</dd>
</dl>
</li>
</ul>
<a name="setReceiver-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setReceiver</h4>
<pre>public&nbsp;void&nbsp;setReceiver(java.lang.String&nbsp;receiver)</pre>
<div class="block">This method is used to sets value of receiver.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>receiver</code> - variable receiver</dd>
</dl>
</li>
</ul>
<a name="getCharge--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getCharge</h4>
<pre>java.lang.Double&nbsp;getCharge()</pre>
<div class="block">This method is used to gets value of charge.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>double value of charge</dd>
</dl>
</li>
</ul>
<a name="setCharge-java.lang.Double-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setCharge</h4>
<pre>public&nbsp;void&nbsp;setCharge(java.lang.Double&nbsp;charge)</pre>
<div class="block">This method is used to sets value of charge.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>charge</code> - variable charge</dd>
</dl>
</li>
</ul>
<a name="getTerm--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getTerm</h4>
<pre>java.util.Date&nbsp;getTerm()</pre>
<div class="block">This method is used to gets value of term.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>date value of variable term</dd>
</dl>
</li>
</ul>
<a name="getTermString--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getTermString</h4>
<pre>java.lang.String&nbsp;getTermString()</pre>
<div class="block">This method is used to gets value of term.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>string value of variable term</dd>
</dl>
</li>
</ul>
<a name="getTimeToDisplay--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getTimeToDisplay</h4>
<pre>java.lang.String&nbsp;getTimeToDisplay()</pre>
<div class="block">This method is used to gets time to display.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>string value of variable term in date format</dd>
</dl>
</li>
</ul>
<a name="getHowManyTimesPayment--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getHowManyTimesPayment</h4>
<pre>java.lang.Integer&nbsp;getHowManyTimesPayment()</pre>
<div class="block">This method is used to gets the number of payments made.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>integer value of variable howManyTimesPayment</dd>
</dl>
</li>
</ul>
<a name="isRepeated--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>isRepeated</h4>
<pre>boolean&nbsp;isRepeated()</pre>
<div class="block">This method is used to determine if payments will be repeated.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>boolean value of variable isRepeated</dd>
</dl>
</li>
</ul>
<a name="getRepetitionPeriod--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getRepetitionPeriod</h4>
<pre>java.lang.String&nbsp;getRepetitionPeriod()</pre>
<div class="block">This method is used to gets value of repetitionPeriod.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>string value of variable repetitionPeriod</dd>
</dl>
</li>
</ul>
<a name="getWhenInform--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getWhenInform</h4>
<pre>java.lang.Integer&nbsp;getWhenInform()</pre>
<div class="block">This method is used to gets value of variable whenInform</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>integer value of variable whenInform</dd>
</dl>
</li>
</ul>
<a name="isisPaid--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>isisPaid</h4>
<pre>public&nbsp;boolean&nbsp;isisPaid()</pre>
<div class="block">This method is used to check if an invoice has been paid.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>boolean value of variable isPaid</dd>
</dl>
</li>
</ul>
<a name="setTerm-java.util.Date-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setTerm</h4>
<pre>private&nbsp;void&nbsp;setTerm(java.util.Date&nbsp;term)</pre>
<div class="block">This method is used to sets value of variable term</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>term</code> - variable term</dd>
</dl>
</li>
</ul>
<a name="getComments--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getComments</h4>
<pre>java.lang.String&nbsp;getComments()</pre>
<div class="block">This method is used to gets comments.</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>string value of comments</dd>
</dl>
</li>
</ul>
<a name="setComments-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setComments</h4>
<pre>public&nbsp;void&nbsp;setComments(java.lang.String&nbsp;comments)</pre>
<div class="block">This method is used to sets comments.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>comments</code> - variable comments</dd>
</dl>
</li>
</ul>
<a name="setHowManyTimesPayment-java.lang.Integer-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setHowManyTimesPayment</h4>
<pre>void&nbsp;setHowManyTimesPayment(java.lang.Integer&nbsp;howManyTimesPayment)</pre>
<div class="block">This method is used to sets value of how many times are payments.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>howManyTimesPayment</code> - variable howManyTimesPayment</dd>
</dl>
</li>
</ul>
<a name="setIsRepeated-boolean-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setIsRepeated</h4>
<pre>void&nbsp;setIsRepeated(boolean&nbsp;isRepeated)</pre>
<div class="block">This method is used to sets value of isRepeated.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>isRepeated</code> - variable isRepeated</dd>
</dl>
</li>
</ul>
<a name="setRepetitionPeriod-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setRepetitionPeriod</h4>
<pre>void&nbsp;setRepetitionPeriod(java.lang.String&nbsp;repetitionPeriod)</pre>
<div class="block">This method is used to sets value of repetitionPeriod.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>repetitionPeriod</code> - variable repetitionPeriod</dd>
</dl>
</li>
</ul>
<a name="setWhenInform-java.lang.Integer-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>setWhenInform</h4>
<pre>void&nbsp;setWhenInform(java.lang.Integer&nbsp;whenInform)</pre>
<div class="block">This method is used to sets value of whenInform.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>whenInform</code> - variable whenInform</dd>
</dl>
</li>
</ul>
<a name="equals-java.lang.Object-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>equals</h4>
<pre>public&nbsp;boolean&nbsp;equals(java.lang.Object&nbsp;o)</pre>
<div class="block">This method is used to comparing object invoice.</div>
<dl>
<dt><span class="overrideSpecifyLabel">Overrides:</span></dt>
<dd><code>equals</code>&nbsp;in class&nbsp;<code>java.lang.Object</code></dd>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>o</code> - is invoice object</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>integer value of compared invoice object variables</dd>
</dl>
</li>
</ul>
<a name="hashCode--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>hashCode</h4>
<pre>public&nbsp;int&nbsp;hashCode()</pre>
<div class="block">This method returns the hashcode value as an Integer.</div>
<dl>
<dt><span class="overrideSpecifyLabel">Overrides:</span></dt>
<dd><code>hashCode</code>&nbsp;in class&nbsp;<code>java.lang.Object</code></dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>integer</dd>
</dl>
</li>
</ul>
<a name="compareTo-java.lang.Object-">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>compareTo</h4>
<pre>public&nbsp;int&nbsp;compareTo(@NonNull
                     java.lang.Object&nbsp;o)</pre>
<dl>
<dt><span class="overrideSpecifyLabel">Specified by:</span></dt>
<dd><code>compareTo</code>&nbsp;in interface&nbsp;<code>java.lang.Comparable</code></dd>
</dl>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../com/example/billsreminderapp/package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-files/index-1.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="../../../com/example/billsreminderapp/CustomAdapter.ViewHolder.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
<li><a href="../../../com/example/billsreminderapp/InvoicesManager.html" title="class in com.example.billsreminderapp"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../../../index.html?com/example/billsreminderapp/Invoice.html" target="_top">Frames</a></li>
<li><a href="Invoice.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li><a href="#field.summary">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#constructor.summary">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li><a href="#field.detail">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#constructor.detail">Constr</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</body>
</html>
