<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_242-release) on Wed Jun 10 21:07:07 CEST 2020 -->
<title>com.example.billsreminderapp</title>
<meta name="date" content="2020-06-10">
<link rel="stylesheet" type="text/css" href="../../../stylesheet.css" title="Style">
<script type="text/javascript" src="../../../script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="com.example.billsreminderapp";
        }
    }
    catch(err) {
    }
//-->
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../com/example/billsreminderapp/package-summary.html">Package</a></li>
<li>Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-files/index-1.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li>Prev&nbsp;Package</li>
<li>Next&nbsp;Package</li>
</ul>
<ul class="navList">
<li><a href="../../../index.html?com/example/billsreminderapp/package-summary.html" target="_top">Frames</a></li>
<li><a href="package-summary.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<div class="header">
<h1 title="Package" class="title">Package&nbsp;com.example.billsreminderapp</h1>
</div>
<div class="contentContainer">
<ul class="blockList">
<li class="blockList">
<table class="typeSummary" border="0" cellpadding="3" cellspacing="0" summary="Class Summary table, listing classes, and an explanation">
<caption><span>Class Summary</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Class</th>
<th class="colLast" scope="col">Description</th>
</tr>
<tbody>
<tr class="altColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/AddActivity.html" title="class in com.example.billsreminderapp">AddActivity</a></td>
<td class="colLast">
<div class="block">Class responsible for adding new invoice to list.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/Cache.html" title="class in com.example.billsreminderapp">Cache</a></td>
<td class="colLast">
<div class="block">Cache storage class used to handle invoices</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/CustomAdapter.html" title="class in com.example.billsreminderapp">CustomAdapter</a></td>
<td class="colLast">
<div class="block">Class responsible for display invoices data in main layout (receiver,charge,datePayment,comments)</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/CustomAdapter.ViewHolder.html" title="class in com.example.billsreminderapp">CustomAdapter.ViewHolder</a></td>
<td class="colLast">
<div class="block">Class that stores data displayed on main activity.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/Invoice.html" title="class in com.example.billsreminderapp">Invoice</a></td>
<td class="colLast">
<div class="block">Invoice class represents class definition</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/InvoicesManager.html" title="class in com.example.billsreminderapp">InvoicesManager</a></td>
<td class="colLast">
<div class="block">This class responsible for write date to Json</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/MainActivity.html" title="class in com.example.billsreminderapp">MainActivity</a></td>
<td class="colLast">
<div class="block">The Main Activity is used to display the application layout resources.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/NotificationReceiver.html" title="class in com.example.billsreminderapp">NotificationReceiver</a></td>
<td class="colLast">
<div class="block">This class responsible for constructing the appearance of the reminder</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/NotificationSetter.html" title="class in com.example.billsreminderapp">NotificationSetter</a></td>
<td class="colLast">
<div class="block">This class is responsible for setting the reminder</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/RepeatingActivity.html" title="class in com.example.billsreminderapp">RepeatingActivity</a></td>
<td class="colLast">
<div class="block">This class is represent Repeating Activity</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><a href="../../../com/example/billsreminderapp/WelcomeActivity.html" title="class in com.example.billsreminderapp">WelcomeActivity</a></td>
<td class="colLast">
<div class="block">The Welcome Activity presents the authors of the project using a splash screen.</div>
</td>
</tr>
</tbody>
</table>
</li>
</ul>
</div>
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../com/example/billsreminderapp/package-summary.html">Package</a></li>
<li>Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../index-files/index-1.html">Index</a></li>
<li><a href="../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li>Prev&nbsp;Package</li>
<li>Next&nbsp;Package</li>
</ul>
<ul class="navList">
<li><a href="../../../index.html?com/example/billsreminderapp/package-summary.html" target="_top">Frames</a></li>
<li><a href="package-summary.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</body>
</html>
